export default {
  ageGroup: ["0 to 5", "6 to 9", "10 to 12", "13 to 17", "18 to 59", "60+"],
  infraType: [
    "School",
    "Church / Place of Worship",
    "Covered Court",
    "Barangay Hall",
    "Barangay Health Station",
    "Evacuation Center",
    "Bridges",
    "Roads",
    "Market",
    "Electricity",
    "Water",
    "Hospital",
    "Seaport / Airport",
    "Communication Lines",
    "Livelihood Facilities",
    "Others"
  ],
  houseType: ["Concrete", "Semi-Concrete", "Light Materials"],
  needsType: [
    "Kitchen Materials",
    "Sleeping Kits",
    "Plastic Sheets / Trapal",
    "Hygiene Kits",
    "House Repair Kits",
    "Clothes",
    "Jerry Can / Water Filter",
    "Others"
  ],
  livelihoodType: [
    "Farming",
    "Fishing",
    "Transportation",
    "Entrepreneurship",
    "Workers"
  ],
  livelihoodSubtype: [
    "Rice",
    "Corn",
    "Vegetables",
    "Fruits",
    "Livestock",
    "Others",
    "Boat",
    "Fishing Equipment",
    "Aquacultures",
    "Others",
    "Jeepney",
    "Tricycle",
    "Van",
    "Others",
    "Employees",
    "Laborers"
  ],
  specialNeedsType: [
    "Pregnant Women",
    "Lactating Mothers",
    "Physically Challenged",
    "Mentally Challenged",
    "Children",
    "Senior Citizens",
    "Infants",
    "Others"
  ],
  evacuationType: [
    "Evacuation Center Building",
    "Multi-Purpose Hall",
    "Church / Place of Worship",
    "School",
    "Gym",
    "Living with Host Family / Friends",
    "Renting an Apartment",
    "Living in Damaged House",
    "Informal Self-Settled Camp",
    "Emergency Shelter / Makeshift House",
    "Squatting",
    "Others"
  ]
};
